car_app/urls.py
from django.urls import path
from . import views

app_name = 'cars_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('elements/', views.elements, name='elements'),
    path('generic/', views.generic, name='generic'),
    path('cars/create/', views.car_create, name='car_create'),
    path('cars/<int:pk>/', views.car_details, name='car_details'),
    path('cars/<int:pk>/edit/', views.car_edit, name='car_edit'),
    path('cars/<int:pk>/delete/', views.car_delete, name='car_delete'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_app.urls')),
    path('tasks/', include('tasks.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    #READ- RETRIEVE
    path('', views.TaskListView.as_view(), name='task_list'),
    #CREATE
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    #UPDATE
    path('<int:pk>/edit/', views.TaskEditView.as_view(), name='task_edit'),
    #DELETE
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),

]

car_app/models.py
import os
import random

from django.db import models
from django.db.models import Count


def get_filename_ext(filepath):
    # /..../helloworld.jpg
    #helloworld.jpg
    base_name = os.path.basename(filepath)
    #helloworld-> name
    #jpg --> ext
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    print(instance)
    print(filename)
    new_filename= random.randint(1, 9999999999)
    name, ext = get_filename_ext(filename)
    print(name, ext)
    final_converted_name = "{new_filename}{ext}".format(
        new_filename=new_filename, ext=ext
    )
    #9939393932.jpg
    print("final function")
    print(final_converted_name)
    print("cars/{new_filename}/{final_converted_name}".format(
        new_filename=new_filename, final_converted_name=final_converted_name
    ))
    return "cars/{new_filename}/{final_converted_name}".format(
        new_filename=new_filename, final_converted_name=final_converted_name
    )


class CustomCarQuerySet(models.query.QuerySet):
    def get_new(self):
        return self.filter(new=True).order_by('id')[:6]


class CarsManager(models.Manager):
    def get_queryset(self):
        return CustomCarQuerySet(self.model, using=self._db)

    def get_new(self):
        return self.get_queryset().get_new()


class Car(models.Model):
    title = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField(
        default=1991
    )
    model = models.CharField(
        max_length=100
    )
    odometer = models.PositiveIntegerField(
        default=0
    )
    objects = CarsManager()
    image = models.ImageField(
        upload_to=upload_image_path
    )
    new = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return f"{self.title} -> {self.odometer}"

# 234324sfd.jpg

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return  f'{self.title}'

car_app/forms.py
from django import forms

from .models import Car


class CarModelForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

car_app/views.py
from django.shortcuts import (
    render, redirect, get_object_or_404
)

from .forms import CarModelForm
from .models import Car


# FBV --- CBV

# FuncitonBasedView --- ClassBasedView

def index(request):
    cars = Car.objects.get_new()
    return render(request, 'index.html', locals())


def car_create(request):
    form = CarModelForm()
    if request.method == 'POST':
        form = CarModelForm(
            request.POST or None, request.FILES or None
        )
        if form.is_valid():
            new_car = form.save()
            return redirect('cars_app:car_details', pk=new_car.pk)
    return render(request, 'cars/car_create.html', locals())


def car_details(request, pk):
    car = Car.objects.filter(pk=pk).first()
    return render(request, 'cars/car_details.html', locals())


def car_edit(request, pk):
    car = get_object_or_404(Car, pk=pk)
    form = CarModelForm(
        request.POST or None, request.FILES or None,
        instance=car
    )
    if form.is_valid():
        new_car = form.save()
        return redirect(
            'cars_app:car_details', pk=new_car.pk
        )
    return render(request, 'cars/car_edit.html', locals())


def car_delete(request, pk):
    car = get_object_or_404(Car, pk=pk)
    if request.method == 'POST':
        car.delete()
        return redirect('cars_app:index')
    return render(request, 'cars/car_delete.html', locals())


def elements(request):
    return render(request, 'elements.html', locals())


def generic(request):
    return render(request, 'generic.html', locals())




def hellow(request):
    return render(request, 'cars/hellow.html', locals())

tasks/views.py
from django.urls import reverse_lazy
from django.views import generic

from tasks.models import Task


class TaskListView(generic.ListView):
    model = Task
    template_name = 'tasks/task_list.html'
    context_object_name = 'tasks' #object_list


class TaskDetailView(generic.DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = 'tasks/task_create.html'
    fields = ('title', 'description', )
    success_url = reverse_lazy('tasks:task_list')

    def get_success_url(self):
        return reverse_lazy(
            'tasks:task_detail',
            kwargs={'pk': self.object.pk}
        )


class TaskEditView(generic.UpdateView):
    model = Task
    template_name = 'tasks/task_edit.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy(
            'tasks:task_detail',
            kwargs={'pk': self.object.pk}
        )


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = 'tasks/task_delete.html'
    success_url = reverse_lazy('tasks:task_list')

templates/bases.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{% block title %} Main {% endblock title %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="index.html" class="logo">
									<span class="symbol"><img src="{%  static 'images/logo.svg' %}" alt="" /></span><span class="title">Phantom</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="generic.html">Ipsum veroeros</a></li>
							<li><a href="generic.html">Tempus etiam</a></li>
							<li><a href="generic.html">Consequat dolor</a></li>
							<li><a href="elements.html">Elements</a></li>
						</ul>
					</nav>



                {% block content %}

                    <h1> Empty content </h1>

                {% endblock content %}


                <!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<input type="text" name="name" id="name" placeholder="Name" />
										</div>
										<div class="field half">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" placeholder="Message"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="primary" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
									<li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
									<li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
        
			<script src="{%  static 'assets/js/jquery.min.js' %}"></script>
			<script src="{%  static 'assets/js/browser.min.js' %}"></script>
			<script src="{%  static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

templates/cars/car_create.html
{% load static %}


<div class="container">
<form action="{% url 'cars_app:car_create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Create Car </button>
</form>
</div>

templates/cars/car_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cars/car_details.html
{% extends 'bases.html' %}

{% load static %}

{% block title %}
    {{ car.title }} Details
{% endblock title %}

{% block content %}
    <ul>
        <li>{{ car.title }}</li>
        <li>{{ car.model }}</li>
        <li>{{ car.odometer }}</li>
        <li>
            {% if car.image %}
            <img width="500" src="{{ car.image.url }}" alt="">
            {% endif %}
        </li>
        <a href="{% url 'cars_app:car_edit' pk=car.pk %}">
            <button type="button" class="btn btn-primary">Update</button>

        </a>
         <a href="{% url 'cars_app:car_delete' pk=car.pk %}">
        <button type="button" class="btn btn-danger">Delete</button>
        </a>
    </ul>

{% endblock content %}

templates/cars/car_edit.html
{% load static %}


<div class="container">
<form action="{% url 'cars_app:car_edit' pk=car.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Update Car </button>
</form>
</div>

templates/cars/hellow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HEllow</h1>
</body>
</html>

templates/generic.html
{% extends 'bases.html' %}
{% load static %}

{%  block title %} Generic {% endblock title %}

{% block content %}
<!-- Main -->
<div id="main">
    <div class="inner">
        <h1>Generic Page</h1>
        <span class="image main"><img src="{% static 'images/pic13.jpg' %}" alt="" /></span>
        <p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
        <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
    </div>
</div>
{% endblock content %}


templates/index.html
{% extends 'bases.html' %}
{% load static %}

<!-- Main -->
{% block content %}

<div id="main">
    <div class="inner">
        <header>
            <h1>This is Phantom, a free, fully responsive site<br />
            template designed by <a href="http://html5up.net">HTML5 UP</a>.</h1>
            <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
            <a href="{% url 'cars_app:car_create' %}">
                <button> Create Car </button>
            </a>
        </header>
        <section class="tiles">
            {% for car in cars %}
            <article class="style{{ forloop.counter }}">
                <span class="image">
                    <img src="{{ car.image.url }}" alt="" />
                </span>
                <a href="{% url 'cars_app:car_details' pk=car.pk %}">
                    <h2>{{ car.title }}</h2>
                    <div class="content">
                        <p>{{ car.model }}</p>
                        <p>{{ car.odometer }}</p>

                    </div>
                </a>

            </article>
            {% endfor %}
        </section>
    </div>
</div>

{% endblock content %}

templates/tasks/task_create.html
{% load static %}


<div class="container">
<form action="{% url 'tasks:task_create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Create Task </button>
</form>
</div>

templates/tasks/task_delete.html
<form action="{%  url 'tasks:task_delete' pk=task.pk%}" method="POST">
    {% csrf_token %}
    Are you sure want to delete it?
    <input type="submit" value="Delete">
</form>

templates/tasks/task_detail.html
{% extends 'bases.html' %}

{% load static %}

{% block title %}
    {{ task.title }} Details
{% endblock title %}

{% block content %}
    <ul>
        <li>{{ task.title }}</li>
        <li>{{ task.description }}</li>
        <a href="{% url 'tasks:task_edit' pk=task.pk %}">
            <button type="button" class="btn btn-primary">Update</button>

        </a>
         <a href="{% url 'tasks:task_delete' pk=task.pk %}">
        <button type="button" class="btn btn-danger">Delete</button>
        </a>
    </ul>

{% endblock content %}

templates/tasks/task_edit.html
{% load static %}


<div class="container">
<form action="{% url 'tasks:task_edit' pk=task.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Update Task </button>
</form>
</div>

templates/tasks/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
{% for obj in tasks %}
         <a href="{% url 'tasks:task_detail' pk=obj.pk%}">
             <li> {{ obj.title }}</li>
         </a>
        <li> {{ obj.description }}</li>

{% endfor %}
</ul>
</body>
</html>